DEFAULT_SYSTEM_VOLTAGE = 24
DEFAULT_AUTONOMY_DAYS = 1.0
DEFAULT_DOD = 0.5  # 50%
DEFAULT_INVERTER_EFF = 0.92
DEFAULT_BAT_RTE = 0.9
DEFAULT_SUN_HOURS = 4.0
DEFAULT_SURGE_FACTOR = 1.25
DEFAULT_CONTINUOUS_FACTOR = 1.25  # 125% for continuous load ampacity check
